# Database
MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT = 3306
MYSQL_DATABASE_USER = ''
MYSQL_DATABASE_PASSWORD = ''
MYSQL_DATABASE_DB = 'reseed'
MYSQL_DATABASE_CHARSET = "utf8"
MYSQL_USE_UNICODE = True

# Redis
REDIS_URL = "redis://localhost:6379/1"
REDIS_TTL = 2 * 24 * 60 * 60  # 2 days

# Flask
SECRET_KEY = b''
REMEMBER_COOKIE_NAME = 'reseed'
REMEMBER_COOKIE_DURATION = 86400

# Site
TJUPT_TOKEN = ""
TJUPT_SECRET = ""

OURBITS_TOKEN = ""
OURBITS_SECRET = ""

HDCHINA_APIKEY = ""
