# Database
MYSQL_DATABASE_HOST = 'localhost'
MYSQL_DATABASE_PORT = 3306
MYSQL_DATABASE_USER = ''
MYSQL_DATABASE_PASSWORD = ''
MYSQL_DATABASE_DB = 'reseed'
MYSQL_DATABASE_CHARSET = "utf8"
MYSQL_USE_UNICODE = True

# Redis
REDIS_URL = "redis://localhost:6379/1"

TJUPT_TOKEN = ""
TJUPT_SECRET = ""

TOKEN_EXPIRED_TIME = 86400
